### ISSUE TITLE
Bug in start_prod.sh

### ISSUE THREAD

**Issue by michellewang** [NTX-McGill/NeuroTechX-McGill-2021#120]
`start_prod.sh` from commit 5d41aeb5c813a4017620ec5c0bac8e1c3aa6e6dc crashes, see error message below. Resetting to 97b6719 made the error disappear. 
```
B21@B21PC1 MINGW64 ~/Documents/McGill_NeuroTech/NeuroTechX-McGill-2021/software/speller/data_collection_platform/backend (main)
$ ./start_prod.sh
Applying database migrations
Traceback (most recent call last):
  File "c:\users\b21\anaconda3\envs\dcp\lib\runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "c:\users\b21\anaconda3\envs\dcp\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "C:\Users\B21\anaconda3\envs\dcp\Scripts\flask.exe\__main__.py", line 7, in <module>
  File "c:\users\b21\anaconda3\envs\dcp\lib\site-packages\flask\cli.py", line 990, in main
    cli.main(args=sys.argv[1:])
  File "c:\users\b21\anaconda3\envs\dcp\lib\site-packages\flask\cli.py", line 596, in main
    return super().main(*args, **kwargs)
  File "c:\users\b21\anaconda3\envs\dcp\lib\site-packages\click\core.py", line 782, in main
    rv = self.invoke(ctx)
  File "c:\users\b21\anaconda3\envs\dcp\lib\site-packages\click\core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "c:\users\b21\anaconda3\envs\dcp\lib\site-packages\click\core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "c:\users\b21\anaconda3\envs\dcp\lib\site-packages\click\core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "c:\users\b21\anaconda3\envs\dcp\lib\site-packages\click\core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "c:\users\b21\anaconda3\envs\dcp\lib\site-packages\click\decorators.py", line 21, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "c:\users\b21\anaconda3\envs\dcp\lib\site-packages\flask\cli.py", line 439, in decorator
    with __ctx.ensure_object(ScriptInfo).load_app().app_context():
  File "c:\users\b21\anaconda3\envs\dcp\lib\site-packages\flask\cli.py", line 402, in load_app
    app = locate_app(self, import_name, name)
  File "c:\users\b21\anaconda3\envs\dcp\lib\site-packages\flask\cli.py", line 273, in locate_app
    return find_best_app(script_info, module)
  File "c:\users\b21\anaconda3\envs\dcp\lib\site-packages\flask\cli.py", line 68, in find_best_app
    app = call_factory(script_info, app_factory)
  File "c:\users\b21\anaconda3\envs\dcp\lib\site-packages\flask\cli.py", line 119, in call_factory
    return app_factory(*args, **kwargs)
  File "C:\Users\B21\Documents\McGill_NeuroTech\NeuroTechX-McGill-2021\software\speller\data_collection_platform\backend\dcp\__init__.py", line 42, in create_app
    db.create_all()  # creates all db tables (NOTE: will not recreate tables that already exist)
  File "c:\users\b21\anaconda3\envs\dcp\lib\site-packages\flask_sqlalchemy\__init__.py", line 1094, in create_all
    self._execute_for_all_tables(app, bind, 'create_all')
  File "c:\users\b21\anaconda3\envs\dcp\lib\site-packages\flask_sqlalchemy\__init__.py", line 1086, in _execute_for_all_tables
    op(bind=self.get_engine(app, bind), **extra)
  File "c:\users\b21\anaconda3\envs\dcp\lib\site-packages\flask_sqlalchemy\__init__.py", line 1017, in get_engine
    return connector.get_engine()
  File "c:\users\b21\anaconda3\envs\dcp\lib\site-packages\flask_sqlalchemy\__init__.py", line 594, in get_engine
    self._engine = rv = self._sa.create_engine(sa_url, options)
  File "c:\users\b21\anaconda3\envs\dcp\lib\site-packages\flask_sqlalchemy\__init__.py", line 1027, in create_engine
    return sqlalchemy.create_engine(sa_url, **engine_opts)
  File "<string>", line 2, in create_engine
  File "c:\users\b21\anaconda3\envs\dcp\lib\site-packages\sqlalchemy\util\deprecations.py", line 298, in warned
    return fn(*args, **kwargs)
  File "c:\users\b21\anaconda3\envs\dcp\lib\site-packages\sqlalchemy\engine\create.py", line 636, in create_engine
    raise TypeError(
TypeError: Invalid argument(s) 'timeout' sent to create_engine(), using configuration PGDialect_psycopg2/QueuePool/Engine.  Please check that the keyword arguments are appropriate for this combination of components.
 * Serving Flask app 'dcp' (lazy loading)
 * Environment: production
   WARNING: This is a development server. Do not use it in a production deployment.
   Use a production WSGI server instead.
 * Debug mode: off
Traceback (most recent call last):
  File "c:\users\b21\anaconda3\envs\dcp\lib\runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "c:\users\b21\anaconda3\envs\dcp\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "C:\Users\B21\anaconda3\envs\dcp\Scripts\flask.exe\__main__.py", line 7, in <module>
  File "c:\users\b21\anaconda3\envs\dcp\lib\site-packages\flask\cli.py", line 990, in main
    cli.main(args=sys.argv[1:])
  File "c:\users\b21\anaconda3\envs\dcp\lib\site-packages\flask\cli.py", line 596, in main
    return super().main(*args, **kwargs)
  File "c:\users\b21\anaconda3\envs\dcp\lib\site-packages\click\core.py", line 782, in main
    rv = self.invoke(ctx)
  File "c:\users\b21\anaconda3\envs\dcp\lib\site-packages\click\core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "c:\users\b21\anaconda3\envs\dcp\lib\site-packages\click\core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "c:\users\b21\anaconda3\envs\dcp\lib\site-packages\click\core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "c:\users\b21\anaconda3\envs\dcp\lib\site-packages\click\decorators.py", line 73, in new_func
    return ctx.invoke(f, obj, *args, **kwargs)
  File "c:\users\b21\anaconda3\envs\dcp\lib\site-packages\click\core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "c:\users\b21\anaconda3\envs\dcp\lib\site-packages\flask\cli.py", line 845, in run_command
    app = DispatchingApp(info.load_app, use_eager_loading=eager_loading)
  File "c:\users\b21\anaconda3\envs\dcp\lib\site-packages\flask\cli.py", line 321, in __init__
    self._load_unlocked()
  File "c:\users\b21\anaconda3\envs\dcp\lib\site-packages\flask\cli.py", line 346, in _load_unlocked
    self._app = rv = self.loader()
  File "c:\users\b21\anaconda3\envs\dcp\lib\site-packages\flask\cli.py", line 402, in load_app
    app = locate_app(self, import_name, name)
  File "c:\users\b21\anaconda3\envs\dcp\lib\site-packages\flask\cli.py", line 273, in locate_app
    return find_best_app(script_info, module)
  File "c:\users\b21\anaconda3\envs\dcp\lib\site-packages\flask\cli.py", line 68, in find_best_app
    app = call_factory(script_info, app_factory)
  File "c:\users\b21\anaconda3\envs\dcp\lib\site-packages\flask\cli.py", line 119, in call_factory
    return app_factory(*args, **kwargs)
  File "C:\Users\B21\Documents\McGill_NeuroTech\NeuroTechX-McGill-2021\software\speller\data_collection_platform\backend\dcp\__init__.py", line 42, in create_app
    db.create_all()  # creates all db tables (NOTE: will not recreate tables that already exist)
  File "c:\users\b21\anaconda3\envs\dcp\lib\site-packages\flask_sqlalchemy\__init__.py", line 1094, in create_all
    self._execute_for_all_tables(app, bind, 'create_all')
  File "c:\users\b21\anaconda3\envs\dcp\lib\site-packages\flask_sqlalchemy\__init__.py", line 1086, in _execute_for_all_tables
    op(bind=self.get_engine(app, bind), **extra)
  File "c:\users\b21\anaconda3\envs\dcp\lib\site-packages\flask_sqlalchemy\__init__.py", line 1017, in get_engine
    return connector.get_engine()
  File "c:\users\b21\anaconda3\envs\dcp\lib\site-packages\flask_sqlalchemy\__init__.py", line 594, in get_engine
    self._engine = rv = self._sa.create_engine(sa_url, options)
  File "c:\users\b21\anaconda3\envs\dcp\lib\site-packages\flask_sqlalchemy\__init__.py", line 1027, in create_engine
    return sqlalchemy.create_engine(sa_url, **engine_opts)
  File "<string>", line 2, in create_engine
  File "c:\users\b21\anaconda3\envs\dcp\lib\site-packages\sqlalchemy\util\deprecations.py", line 298, in warned
    return fn(*args, **kwargs)
  File "c:\users\b21\anaconda3\envs\dcp\lib\site-packages\sqlalchemy\engine\create.py", line 636, in create_engine
    raise TypeError(
TypeError: Invalid argument(s) 'timeout' sent to create_engine(), using configuration PGDialect_psycopg2/QueuePool/Engine.  Please check that the keyword arguments are appropriate for this combination of components.
```

**Comment by mlej8** [comment]
ok I'll fix that soon

**Comment by mlej8** [comment]
solved thanks @michellewang !
